-- Script SQL para configurar as tabelas no Databricks
-- Execute este script no SQL Editor do seu Workspace do Databricks

-- Tabela de Escalas de Sexta-feira
CREATE TABLE IF NOT EXISTS escalas_sexta (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome STRING NOT NULL,
  email STRING,
  data DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
) TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');

-- Tabela de Feriados
CREATE TABLE IF NOT EXISTS feriados (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_colaborador STRING NOT NULL,
  email STRING,
  nome_feriado STRING NOT NULL,
  data DATE NOT NULL,
  time STRING NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
) TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');

-- Dados de exemplo (opcional)
INSERT INTO escalas_sexta (nome, data) VALUES
    ('João Silva', '2026-01-31'),
    ('Maria Santos', '2026-02-07');

INSERT INTO feriados (nome_colaborador, nome_feriado, data, time) VALUES
    ('Pedro Oliveira', 'Carnaval', '2026-02-16', 'SEO'),
    ('Ana Costa', 'Sexta-feira Santa', '2026-04-03', 'FrontEnd');
