# Script para criar as tabelas no Databricks via Python
import os
from databricks import sql
from dotenv import load_dotenv

load_dotenv()

DATABRICKS_SERVER_HOSTNAME = os.getenv("DATABRICKS_SERVER_HOSTNAME")
DATABRICKS_HTTP_PATH = os.getenv("DATABRICKS_HTTP_PATH")
DATABRICKS_TOKEN = os.getenv("DATABRICKS_TOKEN")

def setup_database():
    """Configura as tabelas no Databricks"""
    
    if not DATABRICKS_TOKEN:
        print("❌ DATABRICKS_TOKEN não configurada no arquivo .env!")
        return

    print("🔧 Configurando banco de dados no Databricks...")
    
    try:
        with sql.connect(
            server_hostname=DATABRICKS_SERVER_HOSTNAME,
            http_path=DATABRICKS_HTTP_PATH,
            access_token=DATABRICKS_TOKEN
        ) as connection:
            with connection.cursor() as cursor:
                # SQL para criar as tabelas
                
                print("Criando tabela escalas_sexta...")
                cursor.execute("""
                CREATE TABLE IF NOT EXISTS escalas_sexta (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  nome STRING NOT NULL,
                  email STRING,
                  data DATE NOT NULL,
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
                  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
                )
                TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')
                """)

                print("Criando tabela feriados...")
                cursor.execute("""
                CREATE TABLE IF NOT EXISTS feriados (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  nome_colaborador STRING NOT NULL,
                  email STRING,
                  nome_feriado STRING NOT NULL,
                  data DATE NOT NULL,
                  time STRING NOT NULL,
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
                  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
                )
                TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')
                """)
                # In Databricks we cannot easily add check constraints in Delta like we did in postgres, but we can manage that logically. 
                # Constraints can be added with ALTER TABLE ADD CONSTRAINT time_chk CHECK (time IN ('Cadastro', 'SEO', 'FrontEnd'))
                # We'll skip constraints in the default DDL for simplicity and compatibility unless required.

                print("\n✅ Banco de dados configurado com sucesso!")
                
    except Exception as e:
        print(f"❌ Erro ao configurar banco de dados: {e}")

if __name__ == "__main__":
    setup_database()
